CREATE OR ALTER PROCEDURE TOURNAMENT_TRACKER.USP_ADD_PRIZE
	@PLACE_NUMBER INT,
	@PLACE_NAME NVARCHAR(50),
	@PRIZE_AMOUNT MONEY,
	@PRIZE_PERCENTAGE FLOAT,
	@ID INT = 0 OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO TOURNAMENT_TRACKER.PRIZES(PLACE_NUMBER, PLACE_NAME, PRIZE_AMOUNT, PRIZE_PERCENTAGE)
	VALUES (@PLACE_NUMBER, @PLACE_NAME, @PRIZE_AMOUNT, @PRIZE_PERCENTAGE)

	SELECT @ID = SCOPE_IDENTITY();
END
GO