CREATE OR ALTER PROCEDURE TOURNAMENT_TRACKER.USP_ADD_TEAM
	@TEAM_NAME NVARCHAR(100),
	@ID INT = 0 OUTPUT
AS
BEGIN
	INSERT INTO TOURNAMENT_TRACKER.TEAMS(TEAM_NAME)
	VALUES(@TEAM_NAME);

	SELECT @ID = SCOPE_IDENTITY();
END