CREATE OR ALTER PROCEDURE TOURNAMENT_TRACKER.USP_ADD_TEAM_MEMBER
	@TEAM_ID INT,
	@PERSON_ID INT,
	@ID INT = 0 OUTPUT
AS
BEGIN
	INSERT INTO TOURNAMENT_TRACKER.TEAM_MEMBERS(TEAM_ID, PERSON_ID)
	VALUES(@TEAM_ID, @PERSON_ID);

	SELECT @ID = SCOPE_IDENTITY();
END