CREATE OR ALTER PROCEDURE [TOURNAMENT_TRACKER].[USP_GET_TEAM_MEMBERS_BY_TEAM]
	@TEAM_ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		P.ID AS Id,
		P.FIRST_NAME as FirstName,
		P.LAST_NAME as LastName
	FROM TOURNAMENT_TRACKER.TEAM_MEMBERS AS TM
		JOIN TOURNAMENT_TRACKER.PERSONS AS P
			ON P.ID = TM.PERSON_ID
END
