CREATE OR ALTER PROCEDURE [TOURNAMENT_TRACKER].[USP_ADD_TOURNAMENT_PRIZE]
	@TOURNAMENT_ID INT,
	@PRIZE_ID INT,
	@ID INT = 0 OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO TOURNAMENT_TRACKER.TOURNAMENT_PRIZES(TOURNAMENT_ID, PRIZE_ID)
	VALUES (@TOURNAMENT_ID, @PRIZE_ID)

	SELECT @ID = SCOPE_IDENTITY();
END
