CREATE OR ALTER PROCEDURE [TOURNAMENT_TRACKER].[USP_ADD_TOURNAMENT_ENTRY]
	@TOURNAMENT_ID INT,
	@TEAM_ID INT,
	@ID INT = 0 OUTPUT
AS
BEGIN
	SET NOCOUNT ON;

	INSERT INTO TOURNAMENT_TRACKER.TOURNAMENT_ENTRIES(TOURNAMENT_ID, TEAM_ID)
	VALUES (@TOURNAMENT_ID, @TEAM_ID)

	SELECT @ID = SCOPE_IDENTITY();
END
