CREATE OR ALTER PROCEDURE TOURNAMENT_TRACKER.USP_ADD_MATCHUP_ENTRY
	@MATCHUP_ID INT,
	@PARENT_MATCHUP_ID INT,
	@TEAM_COMPETING_ID INT,
	@ID INT = 0 OUTPUT
AS
BEGIN
	SET NOCOUNT ON;
	-- we dont know the winner yet so it's NULL
	INSERT INTO TOURNAMENT_TRACKER.MATCHUP_ENTRIES(MATCHUP_ID, PARENT_MATCHUP_ID, TEAM_COMPETING_ID)
	VALUES (@MATCHUP_ID, @PARENT_MATCHUP_ID, @TEAM_COMPETING_ID)

	SELECT @ID = SCOPE_IDENTITY();
END
GO