CREATE OR ALTER PROCEDURE [TOURNAMENT_TRACKER].[USP_GET_TOURNAMENT_ALL]
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		ID AS Id,
		ENTRY_FEE AS EntryFee,
		TOURNAMENT_NAME as TournamentName
	FROM TOURNAMENT_TRACKER.TOURNAMENTS
	WHERE ACTIVE = 1;
END