CREATE OR ALTER PROCEDURE [TOURNAMENT_TRACKER].[USP_GET_PRIZES_BY_TOURNAMENT]
	@TOURNAMENT_ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		P.ID AS Id,
		P.PLACE_NUMBER AS PlaceNumber,
		P.PLACE_NAME AS PlaceName,
		P.PRIZE_AMOUNT AS PrizeAmount,
		P.PRIZE_PERCENTAGE AS PrizePercentage
	FROM TOURNAMENT_TRACKER.TOURNAMENT_PRIZES AS TP
		JOIN TOURNAMENT_TRACKER.PRIZES AS P
			ON P.ID = TP.PRIZE_ID
	WHERE TOURNAMENT_ID = @TOURNAMENT_ID;
END