CREATE OR ALTER PROCEDURE [TOURNAMENT_TRACKER].[USP_GET_TEAMS_BY_TOURNAMENT]
	@TOURNAMENT_ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		T.ID AS Id,
		T.TEAM_NAME AS TeamName
	FROM TOURNAMENT_TRACKER.TOURNAMENT_ENTRIES AS TE
		JOIN TOURNAMENT_TRACKER.TEAMS AS T
			ON T.ID = TE.TEAM_ID
	WHERE TOURNAMENT_ID = @TOURNAMENT_ID;
END