CREATE OR ALTER PROCEDURE [TOURNAMENT_TRACKER].[USP_GET_MATCHUPS_BY_TOURNAMENT]
	@TOURNAMENT_ID INT
AS
BEGIN
	SET NOCOUNT ON;

	SELECT
		M.ID AS Id,
		M.WINNER_ID AS WinnerId,
		M.MATCHUP_ROUND AS MatchupRound
	FROM TOURNAMENT_TRACKER.MATCHUPS AS M
	WHERE TOURNAMENT_ID = @TOURNAMENT_ID
	ORDER BY MATCHUP_ROUND ASC;
END