CREATE OR ALTER PROCEDURE TOURNAMENT_TRACKER.USP_UPDATE_MATCHUPS
	@ID INT,
	@WINNER_ID INT
AS
BEGIN
	SET NOCOUNT ON;

	UPDATE TOURNAMENT_TRACKER.MATCHUPS
		SET WINNER_ID = @WINNER_ID
	WHERE ID = @ID;
END